server:
  port: 8080
  error:
    include-message: always

spring:
  boot:
    admin:
      client:
        enabled: true
        instance:
          service-url: http://microservice-streaming:8080

  liquibase:
    enabled: false
    drop-first: false
    change-log: classpath:database-streaming-changelog.xml

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false
      acks: 1

kafka-topics:
  topic_test: topic_test
  streaming_dialogs: streaming_dialogs
  streaming_account: streaming_account

  dialogs_streaming: dialogs_streaming
  notifications_streaming: notification_streaming



kafka-groupId: microservice-streaming
kafka-concurrency: 5
kafka-pollTimeout: 2000
acks-timeout-mseconds: 2000
pong_interval: 10000
socket_path: ${SOCKET_PATH:api/v1/streaming/ws}

java:
  concurrent:
    corePoolSize: 10
    maximumPoolSize: 20
    queueCapacity: 200
    keepAliveSeconds: 60
